import time

print("           Tic Tac Toe\n")
time.sleep(1)
print("          -------------\n          |   |   |   |\n          -------------\n          |   |   |   |\n          -------------\n          |   |   |   |\n          -------------")


print("\n    Player One will always be the X")
time.sleep(1)
p1 = str(input("\n      Enter Name (Player One)\n\n            "))
time.sleep(1)
p2 = str(input("\n      Enter Name (Player Two)\n\n            "))

print("\n           Tic Tac Toe")
def game():
    ged = ("          -------------\n          | 1 | 2 | 3 |\n          -------------\n          | 4 | 5 | 6 |\n          -------------\n          | 7 | 8 | 9 |\n          -------------")
    print(ged)
game()
time.sleep(1)
f1 = str(input("\nplease choose a number " + p1 +"\n\n                "))
exh = ged.replace(f1, "x")
print(exh)
time.sleep(1)
f2 = str(input("\nplease choose a number " + p2 +"\n\n                "))
ex = exh.replace(f2, "/")
print(ex)
time.sleep(1)
f1 = str(input("\nplease choose a number " + p1 +"\n\n                "))
exh = ex.replace(f1, "x")
print(exh)
time.sleep(1)    
f2 = str(input("\nplease choose a number " + p2 +"\n\n                "))
ex = exh.replace(f2 , "/")
print(ex)
time.sleep(1)
f1 = str(input("\nplease choose a number " + p1 +"\n\n                "))
exh = ex.replace(f1, "x")
print(exh)
time.sleep(1)
f2 = str(input("\nplease choose a number " + p2 +"\n\n                "))
ex = exh.replace(f2, "/")
print(ex)
time.sleep(1)
f1 = str(input("\nplease choose a number" + p1 +"\n\n                "))
exh = ex.replace(f1, "x")
print(exh)
time.sleep(1)
f2 = str(input("\nplease choose a number " + p2 + "\n\n                "))
ex = exh.replace(f2 , "/")
print(ex)
time.sleep
f1 = str(input("\nplease choose a number " + p1 + "\n\n                "))
exh = ex.replace(f1, "x")
print(exh)